### ISSUE TITLE
Proper exit process

### ISSUE THREAD

**Issue by GiuseppeCesarano** [GiuseppeCesarano/just-fast#2]
When _Just Fast_ is closed a print of the last screen appears in the terminal. I would like a blank line to appear instead

**Comment by ArthurSonzogni** [comment]
Yes, this sounds like a bug in FTXUI. I will have a look.

**Comment by ArthurSonzogni** [comment]
This should be fixed in theory.

Thanks for filling this issue. This forced me to address one TODO I left.

**Comment by GiuseppeCesarano** [comment]
Unlucky i still see a full print of the last screen when closing the application

**Comment by ArthurSonzogni** [comment]
That's the expected behavior.

So, I guess you would like an option to save/restore the terminal. I will take a look.

**Comment by GiuseppeCesarano** [comment]
Exactly, I didn't look enough but maybe changing the screen size and clearing it before killing the screen loop can be the solution

**Comment by ArthurSonzogni** [comment]
Done.
This is a nice addition to FTXUI! Thanks for filling this issue!
